import os
import re
import zipfile
from flask import Flask, render_template, request

app = Flask(__name__)

# AI-generated patterns
ai_patterns = [
    "Generated by ChatGPT", "Generated by Copilot", "AI-generated",
    "As an AI language model", "This function does the following",
    "This script", "Auto-generated", "This function is designed to",
    "Generated using AI", "Generated by an AI assistant",
    "// AI-generated", "// Generated by ChatGPT", "// Auto-generated by AI",
    "/* AI-generated */", "/* Generated by Copilot */",
    "<!-- AI-generated -->", "<!-- Generated by ChatGPT -->"
]

# File types to check
file_extensions = (".py", ".php", ".html", ".css", ".js", ".java", ".c", ".cpp")

def detect_ai_generated_code(directory):
    suspicious_files = []

    # Walk through files
    for root, _, files in os.walk(directory):
        for file_name in files:
            if file_name.endswith(file_extensions):
                file_path = os.path.join(root, file_name)
                try:
                    with open(file_path, "r", encoding="utf-8", errors="ignore") as file:
                        content = file.read()
                        for pattern in ai_patterns:
                            if re.search(pattern, content, re.IGNORECASE):
                                suspicious_files.append(file_name)
                                break
                except Exception as e:
                    print(f"Could not read {file_path}: {e}")

    return suspicious_files

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        if "file" not in request.files:
            return "No file uploaded."

        file = request.files["file"]

        if file.filename == "":
            return "No selected file."

        if file and file.filename.endswith(".zip"):
            zip_path = os.path.join("uploads", file.filename)
            extract_path = os.path.join("uploads", "extracted")

            os.makedirs("uploads", exist_ok=True)
            os.makedirs(extract_path, exist_ok=True)

            file.save(zip_path)

            # Extract zip file
            with zipfile.ZipFile(zip_path, "r") as zip_ref:
                zip_ref.extractall(extract_path)

            # Scan for AI-generated code
            results = detect_ai_generated_code(extract_path)

            return render_template("result.html", results=results)

    return render_template("index.html")

if __name__ == "__main__":
    app.run(debug=True)
